# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8
  - 3.9

install:
  - pip install -r requirements.txt
  - export PYTHONPATH=$(pwd)
# command to run tests
script:
  - python acq/acq_main.py


