# Config file for automatic testing at travis-ci.com

language: python
jobs:
  include:
    - name: "Python on macOS"
      os: osx
      osx_image: xcode11.6
      language: shell       # 'language: python' is an error on Travis CI macOS

install:
  - pip install -r requirements.txt
  - export PYTHONPATH=$(pwd)
# command to run tests
script:
  - python acq/acq_main.py


